"""add_performance_indexes_for_common_queries

Revision ID: 5294402d81ae
Revises: d3133ef98f6e
Create Date: 2025-10-10 09:36:26.856199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5294402d81ae'
down_revision: Union[str, Sequence[str], None] = 'd3133ef98f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_oauth2_client_active_created', 'oauth2_clients', ['is_active', 'created_at'], unique=False)
    op.create_index('idx_oauth2_client_is_active', 'oauth2_clients', ['is_active'], unique=False)
    op.create_index(op.f('ix_oauth2_clients_is_active'), 'oauth2_clients', ['is_active'], unique=False)
    op.create_index('idx_permission_resource_action', 'permissions', ['resource', 'action'], unique=False)
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index('idx_user_tokens_active', 'user_tokens', ['user_id', 'is_revoked', 'expires_at'], unique=False)
    op.create_index('idx_user_active_created', 'users', ['is_active', 'created_at'], unique=False)
    op.create_index('idx_user_is_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index('idx_user_is_active', table_name='users')
    op.drop_index('idx_user_active_created', table_name='users')
    op.drop_index('idx_user_tokens_active', table_name='user_tokens')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_index('idx_permission_resource_action', table_name='permissions')
    op.drop_index(op.f('ix_oauth2_clients_is_active'), table_name='oauth2_clients')
    op.drop_index('idx_oauth2_client_is_active', table_name='oauth2_clients')
    op.drop_index('idx_oauth2_client_active_created', table_name='oauth2_clients')
    # ### end Alembic commands ###
